### ISSUE TITLE
This Application is pretty cool ! I think, do you know how I can run it on Android 6.0, Since I see it minSDK version is 7.0.

### ISSUE THREAD

**Issue by KOKOAs** [Magicboomliu/Graduation_Project-SCUT-#1]

**Comment by Magicboomliu** [comment]
Thank you for your attention. About your concern,  You can change the gradle file or just change the android Mainfest File of the project. You can change the minSDK version to 16 which will enable it on machines below Android 7.  I hope it will help you.

**Comment by Magicboomliu** [comment]
Android SDK  is all adjustable
